import IVisit from "../models/IVisit";

export const visits: IVisit[] = [
    {
    id: 1,
    serviceType: null,
    cabinet: "102A",
    beginTime: "2023-02-15T12:50:00Z",
    endTime: "2023-02-15T12:50:00Z",
    appealInfo: null,
    status: "OK",
    result: "result",
    client: {
        id: 101,
        password: "srbstsrnsrn",
        firstName: "Vasya",
        sureName: "Pupkin",
        secondName: "Petrovich",
        email: "123@123.ru",
        age: 30,
    },
    doctor: {
        id: 201,
        password: "234234",
        username: "terminator",
        firstName: "Aristarh",
        sureName: "Olegovich",
        secondName: "Petrov",
        specification: "proktologoanatom",
    },
},

    {
    id: 2,
    serviceType: null,
    cabinet: "102A",
    beginTime: "2023-02-15T12:50:00Z",
    endTime: "2023-02-15T12:50:00Z",
    appealInfo: null,
    status: "OK",
    result: "result",
    client: {
        id: 101,
        password: "srbstsrnsrn",
        firstName: "Vasya",
        sureName: "Pupkin",
        secondName: "Petrovich",
        email: "123@123.ru",
        age: 30,
    },
    doctor: {
        id: 201,
        password: "234234",
        username: "terminator",
        firstName: "Aristarh",
        sureName: "Olegovich",
        secondName: "Petrov",
        specification: "proktologoanatom",
    },
},

    {
        id: 3,
        serviceType: null,
        cabinet: "102A",
        beginTime: "2023-02-15T12:50:00Z",
        endTime: "2023-02-15T12:50:00Z",
        appealInfo: null,
        status: "OK",
        result: "result",
        client: {
            id: 101,
            password: "srbstsrnsrn",
            firstName: "Vasya",
            sureName: "Pupkin",
            secondName: "Petrovich",
            email: "123@123.ru",
            age: 30,
        },
        doctor: {
            id: 201,
            password: "234234",
            username: "terminator",
            firstName: "Aristarh",
            sureName: "Olegovich",
            secondName: "Petrov",
            specification: "proktologoanatom",
        },
    },

    {
        id: 4,
        serviceType: null,
        cabinet: "102A",
        beginTime: "2023-02-15T12:50:00Z",
        endTime: "2023-02-15T12:50:00Z",
        appealInfo: null,
        status: "OK",
        result: "result",
        client: {
            id: 101,
            password: "srbstsrnsrn",
            firstName: "Vasya",
            sureName: "Pupkin",
            secondName: "Petrovich",
            email: "123@123.ru",
            age: 30,
        },
        doctor: {
            id: 201,
            password: "234234",
            username: "terminator",
            firstName: "Aristarh",
            sureName: "Olegovich",
            secondName: "Petrov",
            specification: "proktologoanatom",
        },
    },

    {
        id: 5,
        serviceType: null,
        cabinet: "102A",
        beginTime: "2023-02-15T12:50:00Z",
        endTime: "2023-02-15T12:50:00Z",
        appealInfo: null,
        status: "OK",
        result: "result",
        client: {
            id: 101,
            password: "srbstsrnsrn",
            firstName: "Vasya",
            sureName: "Pupkin",
            secondName: "Petrovich",
            email: "123@123.ru",
            age: 30,
        },
        doctor: {
            id: 201,
            password: "234234",
            username: "terminator",
            firstName: "Aristarh",
            sureName: "Olegovich",
            secondName: "Petrov",
            specification: "proktologoanatom",
        },
    },

    {
        id: 6,
        serviceType: null,
        cabinet: "102A",
        beginTime: "2023-02-15T12:50:00Z",
        endTime: "2023-02-15T12:50:00Z",
        appealInfo: null,
        status: "OK",
        result: "result",
        client: {
            id: 101,
            password: "srbstsrnsrn",
            firstName: "Vasya",
            sureName: "Pupkin",
            secondName: "Petrovich",
            email: "123@123.ru",
            age: 30,
        },
        doctor: {
            id: 201,
            password: "234234",
            username: "terminator",
            firstName: "Aristarh",
            sureName: "Olegovich",
            secondName: "Petrov",
            specification: "proktologoanatom",
        },
    },

    {
        id: 7,
        serviceType: null,
        cabinet: "102A",
        beginTime: "2023-02-15T12:50:00Z",
        endTime: "2023-02-15T12:50:00Z",
        appealInfo: null,
        status: "OK",
        result: "result",
        client: {
            id: 101,
            password: "srbstsrnsrn",
            firstName: "Vasya",
            sureName: "Pupkin",
            secondName: "Petrovich",
            email: "123@123.ru",
            age: 30,
        },
        doctor: {
            id: 201,
            password: "234234",
            username: "terminator",
            firstName: "Aristarh",
            sureName: "Olegovich",
            secondName: "Petrov",
            specification: "proktologoanatom",
        },
    },

    {
        id: 8,
        serviceType: null,
        cabinet: "102A",
        beginTime: "2023-02-15T12:50:00Z",
        endTime: "2023-02-15T12:50:00Z",
        appealInfo: null,
        status: "OK",
        result: "result",
        client: {
            id: 101,
            password: "srbstsrnsrn",
            firstName: "Vasya",
            sureName: "Pupkin",
            secondName: "Petrovich",
            email: "123@123.ru",
            age: 30,
        },
        doctor: {
            id: 201,
            password: "234234",
            username: "terminator",
            firstName: "Aristarh",
            sureName: "Olegovich",
            secondName: "Petrov",
            specification: "proktologoanatom",
        },
    },

    {
        id: 9,
        serviceType: null,
        cabinet: "102A",
        beginTime: "2023-02-15T12:50:00Z",
        endTime: "2023-02-15T12:50:00Z",
        appealInfo: null,
        status: "OK",
        result: "result",
        client: {
            id: 101,
            password: "srbstsrnsrn",
            firstName: "Vasya",
            sureName: "Pupkin",
            secondName: "Petrovich",
            email: "123@123.ru",
            age: 30,
        },
        doctor: {
            id: 201,
            password: "234234",
            username: "terminator",
            firstName: "Aristarh",
            sureName: "Olegovich",
            secondName: "Petrov",
            specification: "proktologoanatom",
        },
    },
];

